# parameters
nc: 2  # number of classes
depth_multiple: 0.67  # model depth multiple
width_multiple: 1.00  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# ESNet
backbone:
  # [from, number, module, args]
  [ [ -1, 1, CBH, [ 48, 3, 2 ] ],    # 0-P2/4
    [ -1, 1, ES_Bottleneck, [ 96, 2 ] ], # 1-P3/8
    [ -1, 3, ES_Bottleneck, [ 96, 1 ] ], # 2
    [ -1, 1, ES_Bottleneck, [ 192, 2 ] ], # 3-P5/16
    [ -1, 7, ES_Bottleneck, [ 192, 1 ] ], # 4
    [ -1, 1, ES_Bottleneck, [ 384, 2 ] ], # 5-P7/32
    [ -1, 3, ES_Bottleneck, [ 384, 1 ] ], # 6
  ]

#  yolov5 6.0 head
head:
  [ [ -1, 1, Conv, [ 192, 1, 1 ] ], # 7
    [-1, 1, nn.Upsample, [None, 2, 'nearest']],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, C3, [ 192, False ] ],  # 10 (P3/8-small)

    [ -1, 1, Conv, [ 96, 1, 1 ] ], # 11
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
    [ -1, 1,  C3, [ 96, False ] ],  # 14(P3/8-small)

    [ -1, 1, Conv, [ 96, 3, 2 ] ], # 15
    [ [ -1, 11 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, C3, [ 192, False ] ],  # 17 (P4/16-smedium)

    [-1, 1, Conv, [ 192, 3, 2 ]], # 18
    [ [ -1, 7 ], 1, Concat, [ 1 ] ],  # cat head P5
    [ -1, 1, C3, [ 384, False ] ],  # 20 (P5/32-large)
   
    [ [ 14, 17, 20], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
  ]
